# Generated by Django 4.1.1 on 2022-09-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kaiju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('japanese_name', models.CharField(max_length=120)),
                ('species', models.CharField(max_length=120)),
                ('height', models.CharField(max_length=120)),
                ('length', models.CharField(max_length=120)),
                ('weight', models.CharField(max_length=120)),
                ('noise', models.FileField(upload_to='noise/')),
                ('description', models.TextField()),
            ],
        ),
    ]
