# Generated by Django 4.1.1 on 2022-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaiju',
            name='picture',
            field=models.ImageField(default=1, upload_to='picture/'),
            preserve_default=False,
        ),
    ]
