# Generated by Django 4.1.1 on 2022-09-08 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0002_kaiju_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaiju',
            name='picture',
            field=models.TextField(default='No Image'),
        ),
    ]
