# Generated by Django 4.1.1 on 2022-09-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0004_alter_kaiju_noise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaiju',
            name='noise',
            field=models.FileField(upload_to='../noise'),
        ),
        migrations.AlterField(
            model_name='kaiju',
            name='picture',
            field=models.FileField(upload_to='../picture'),
        ),
    ]
