# Generated by Django 4.1.1 on 2022-09-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0005_alter_kaiju_noise_alter_kaiju_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaiju',
            name='noise',
            field=models.FileField(upload_to='noise'),
        ),
        migrations.AlterField(
            model_name='kaiju',
            name='picture',
            field=models.FileField(upload_to='picture'),
        ),
    ]
