# Generated by Django 4.1.1 on 2022-09-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('godzilla', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
